name: portfolio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.0
  firebase_database: ^9.0.14
  file_picker: ^4.5.1
  firebase_storage: ^10.2.11
  flutter_form_builder: ^7.1.1
  cached_network_image: ^3.2.1
  easy_debounce: ^2.0.2+1
  easy_sidemenu: ^0.3.1
  cloud_firestore: ^3.4.4
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.0.9
  html_editor_enhanced: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

